version: '3.8'
services:
  prompt-scorer:
    build: .
    ports:
      - "8000:8000"
      - "8501:8501"
    environment:
      - API_URL=http://localhost:8000/evaluate
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}